In [17]:
import numpy as np
from matplotlib import pyplot as plt
import matplotlib.cm as cm
import scipy
import scipy.misc

def read_image(name):
    image = scipy.misc.imread(name,flatten=True)
    image = scipy.misc.imresize(image,(512,512),'bilinear')
    image = np.where(image > 231, 255)
    image = np.where(image > 208 & image < 230, 209)
    image = np.where(image > 166 & image < 209, 167)
    image = np.where(image > 86 & image < 167, 87)
    image = np.where(image > 49 & image < 87, 50)
    image = np.where(image >= 0 & image < 50, 0)
    #image = np.where(image > 175, 1, -1)
    return image
    
def show_image(image):
    #image = np.where(image > 0, 255, 0)
    plt.imshow(image,cmap=cm.gray)
    plt.show() 
    
def add_noise(image, noise_percent=0.10):
    rows=image.shape[0]    
    cols=image.shape[1]    
    area=rows*cols
    loc_flip=np.random.randint(0,area,int(area*noise_percent))
    for ii in loc_flip:
        locr=int(ii/cols)
        locc=(ii%cols)
        image[locr,locc]=-1*image[locr,locc]
    return image

def ICM(noisy_image):
    h=-1
    beta=1.0
    eta=2.1
    image=noisy_image
    for row in range(image.shape[0]):
        for col in range(image.shape[1]):
            e_plus = compute_energy(noisy_image,image,row,col,1,h,beta,eta) 
            e_minus = compute_energy(noisy_image,image,row,col,-1,h,beta,eta)
            if e_plus < e_minus:
                image[row,col]=1
            else:
                image[row,col]=-1
    return image
        
def compute_energy(noisy_image,image,row,col,label,h,beta,eta):
    energy=h*label
    if row > 0:
        energy -= beta*label*image[row-1,col]
    if col > 0:
        energy -= beta*label*image[row,col-1]
    if col < image.shape[1]-1:
        energy -= beta*label*image[row,col+1]
    if row < image.shape[0]-1:
        energy -= beta*label*image[row+1,col]
    energy -= eta*label*noisy_image[row,col]
    return energy

if __name__=="__main__":
    name="/Users/johanabrahamsson/Documents/Machine learning and data science/Python/lena_gray.jpg"
    image=read_image(name)
    show_image(image)
    noisy_image=add_noise(image,noise_percent=0.10)
    show_image(noisy_image)
    denoised_image=ICM(noisy_image)
    show_image(denoised_image)


/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/ipykernel_launcher.py:8: DeprecationWarning: `imread` is deprecated!
`imread` is deprecated in SciPy 1.0.0, and will be removed in 1.2.0.
Use ``imageio.imread`` instead.
  
/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/ipykernel_launcher.py:9: DeprecationWarning: `imresize` is deprecated!
`imresize` is deprecated in SciPy 1.0.0, and will be removed in 1.2.0.
Use ``skimage.transform.resize`` instead.
  if __name__ == '__main__':


ValueError: either both or neither of x and y should be given

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [20]:
print(image)

[[-1 -1 -1 ... -1 -1 -1]
 [-1 -1 -1 ... -1 -1 -1]
 [-1 -1 -1 ... -1 -1  1]
 ...
 [-1 -1 -1 ... -1 -1 -1]
 [-1 -1 -1 ... -1 -1 -1]
 [-1 -1 -1 ... -1 -1 -1]]


In [28]:
image = scipy.misc.imread(name,flatten=True)
image = scipy.misc.imresize(image,(512,512),'bilinear')
print(image[:10,:10])
print(np.where(image > 100))

[[136 138 139 138 135 134 135 137 144 137]
 [137 138 139 138 136 134 135 137 144 137]
 [138 139 139 138 136 135 136 137 143 137]
 [138 138 138 138 137 136 136 136 142 136]
 [138 137 137 136 136 136 135 135 141 136]
 [137 136 135 135 136 135 134 133 138 135]
 [137 135 133 133 135 135 133 131 136 134]
 [136 134 132 132 134 134 132 130 135 133]
 [129 131 134 136 136 135 133 132 140 135]
 [130 131 133 134 134 132 129 128 135 131]]
(array([  0,   0,   0, ..., 511, 511, 511]), array([  0,   1,   2, ..., 476, 477, 478]))


/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/ipykernel_launcher.py:1: DeprecationWarning: `imread` is deprecated!
`imread` is deprecated in SciPy 1.0.0, and will be removed in 1.2.0.
Use ``imageio.imread`` instead.
  """Entry point for launching an IPython kernel.
/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/ipykernel_launcher.py:2: DeprecationWarning: `imresize` is deprecated!
`imresize` is deprecated in SciPy 1.0.0, and will be removed in 1.2.0.
Use ``skimage.transform.resize`` instead.
  


In [22]:

print(image)

[[135. 137. 138. ... 148. 131.  92.]
 [136. 137. 138. ... 149. 134.  96.]
 [137. 138. 138. ... 149. 135.  96.]
 ...
 [ 20.  21.  24. ...  71.  71.  70.]
 [ 21.  22.  26. ...  68.  70.  73.]
 [ 23.  24.  28. ...  67.  69.  75.]]
